server {
    listen 3001;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://packing-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
