services:
  packing-backend:
    build: ./backend
    container_name: "packing-backend"
    restart: "always"
    env_file: .env
    volumes:
      - "./data:/app/data"
      - "./.env:/app/.env"
    networks:
      - "ollama-network"

  packing-frontend:
    build: ./frontend
    container_name: "packing-frontend"
    restart: "always"
    ports:
      - "3001:3001"
    depends_on:
      - "packing-backend"
    networks:
      - "ollama-network"

networks:
  ollama-network:
    external: true
    name: "ollama-network"
